# Generated by Django 4.2 on 2023-04-17 00:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_tienda', '0002_alter_datosusuario_nrocelular'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProducto', models.CharField(default='000000000', max_length=32)),
                ('codigo', models.CharField(default='000000000', max_length=32)),
                ('precioCompra', models.CharField(default='0', max_length=32)),
                ('PrecioVenta', models.CharField(default='0', max_length=32)),
                ('fechaventa', models.DateField(default=datetime.date.today)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
