# Generated by Django 4.2 on 2023-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tienda', '0003_datosproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosproducto',
            name='stockProducto',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
